services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    JBSNewMedia\AssetComposerBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../Kernel.php'
        tags: [ 'controller.service_arguments' ]

    JBSNewMedia\AssetComposerBundle\Service\AssetComposer:

    JBSNewMedia\AssetComposerBundle\Twig\AssetsComposerExtension:
        arguments:
            $projectDir: '%kernel.project_dir%'
